

- language: generic
  sudo: required
  services:
    - docker
  env:
    - Description="NativeScript docker build"
    - DOCKER_IMAGE="eric7237cire/vocab-nativescript"

  before_install:
    - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
    - docker pull ${DOCKER_IMAGE}:latest
    - docker build --cache-from ${DOCKER_IMAGE}:latest --tag ${DOCKER_IMAGE} .

  script:
    - docker push ${DOCKER_IMAGE}

notifications:
  email: false
